#!/usr/bin/env python
import sys
import os.path

#support running uninstalled
_dirname = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if os.path.exists(os.path.join(_dirname,"NEWS")):
    sys.path.insert(0, _dirname)

import conduit
import conduit.Main

app = conduit.Main.Application()
 
