#! /usr/bin/env python

import sys, os
sys.path.insert(0, '..')

os.environ['TEST_DIRECTORY'] = 'tmp'

from test_datatypes import *
from test_dataprovider import *
from test_synchronization import *

import unittest

if __name__ == "__main__":
    loader = unittest.TestLoader()
    suite = loader.loadTestsFromModule(__import__('__main__'))
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)
    sys.exit(not result.wasSuccessfull())
