#! /usr/bin/env python

import sys, os
sys.path.insert(0, '..')

os.environ['TEST_DIRECTORY'] = 'tmp'

from test_datatypes import *
from test_dataprovider import *
from test_synchronization import *

if __name__ == "__main__":
    import unittest
    unittest.main()
